name: QuestLines
version: '${project.version}'
main: QuestLines.LineQuests.QuestLines
api-version: '1.20'
authors: [JetAbyss]
description: Doing gamer tings.
commands:
  war:
    description: start things
    usage: /<command>